import type { SiteConfig } from '@portfolio/shared';

export const siteConfig: SiteConfig = {
  name: 'Sandra Suh',
  tagline: 'Illustration Artist',
  socialLinks: {
    instagram: '/coming-soon',
    twitter: '/coming-soon',
    bluesky: '/coming-soon',
    email: 'contact@sandrasuh.com'
  },
  navItems: [
    { label: 'Home', path: '/' },
    {
      label: 'Work',
      path: '/category/illustrations',
      children: [
        { label: 'Illustration', path: '/category/illustrations' },
        { label: 'Sketchbook', path: '/category/sketchbook' },
        { label: 'Animation', path: '/category/animation' },
        { label: 'Sculpture', path: '/category/sculptures' },
        { label: 'Concepts', path: '/category/concepts' }
      ]
    },
    { label: 'Commissions', path: '/category/commissions' },
    { label: 'About Me & Contact', path: '/about' }
  ],
  projects: [
    {
      id: 'sketch-skull-butterfly',
      title: 'Skull & Butterfly',
      imageAlt: 'Graphite still-life sketch of a skull topped by a butterfly',
      category: 'sketchbook',
      size: 'medium',
      image: '/assets/sketch-skull-butterfly.jpg',
      aspectRatio: '3 / 4',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/sketch-skull-butterfly'
    },
    {
      id: 'sketch-animal-study',
      title: 'Animal Study',
      imageAlt: 'Graphite animal study featuring a close view of a pair of eyes and a separate shaded form',
      category: 'sketchbook',
      size: 'medium',
      image: '/assets/sketch-animal-study.jpg',
      aspectRatio: '3 / 4',
      objectFit: 'contain',
      showOnHome: true,
      path: '/project/sketch-animal-study'
    },
    {
      id: 'traditional-cat-reference',
      title: 'Cat Reference Study',
      imageAlt: 'Pencil drawing of a cat displayed above the photographic reference used for the study',
      category: 'sketchbook',
      size: 'medium',
      image: '/assets/traditional-cat-reference.jpg',
      aspectRatio: '3 / 4',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/traditional-cat-reference'
    },
    {
      id: 'traditional-floral-sword',
      title: 'Floral Sword',
      imageAlt: 'Hand-painted fantasy sword surrounded by green leaves and red-orange flourishes',
      category: 'sketchbook',
      size: 'medium',
      image: '/assets/traditional-sword.jpg',
      aspectRatio: '2475 / 3979',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/traditional-floral-sword'
    },
    {
      id: 'traditional-adventure-time-style',
      title: 'Adventure Time Style Study',
      imageAlt: 'Hand-painted cartoon character seated at a table in an Adventure Time-inspired style',
      category: 'sketchbook',
      size: 'medium',
      image: '/assets/traditional-adventure-time-style.jpg',
      aspectRatio: '3093 / 2772',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/traditional-adventure-time-style'
    },
    {
      id: 'sketchbook-seated-figure-study',
      title: 'Seated Figure Study',
      imageAlt: 'Pencil figure study of a seated woman with one leg crossed over the other',
      category: 'sketchbook',
      size: 'medium',
      image: '/assets/sketchbook-seated-figure-study.png',
      aspectRatio: '623 / 764',
      objectFit: 'contain',
      showOnHome: false,
      contentWarning: 'Figure Drawing / Nudity',
      path: '/project/sketchbook-seated-figure-study'
    },
    {
      id: 'sketchbook-standing-male-figure-study',
      title: 'Standing Figure Study',
      imageAlt: 'Pencil anatomy study of a nude standing male figure leaning on a staff',
      category: 'sketchbook',
      size: 'medium',
      image: '/assets/sketchbook-standing-male-figure-study.png',
      aspectRatio: '861 / 1148',
      objectFit: 'contain',
      showOnHome: false,
      contentWarning: 'Figure Drawing / Nudity',
      path: '/project/sketchbook-standing-male-figure-study'
    },
    {
      id: 'sketchbook-figure-foot-anatomy-study',
      title: 'Figure & Foot Anatomy Study',
      imageAlt: 'Pencil anatomy studies of a nude standing figure and two detailed feet',
      category: 'sketchbook',
      size: 'medium',
      image: '/assets/sketchbook-figure-foot-anatomy-study.png',
      aspectRatio: '615 / 527',
      objectFit: 'contain',
      showOnHome: false,
      contentWarning: 'Figure Drawing / Nudity',
      path: '/project/sketchbook-figure-foot-anatomy-study'
    },
    {
      id: 'sculpture-creature-front',
      title: 'Wearable Cardboard Creature — Front View',
      imageAlt: 'Front view of a wearable cardboard creature sculpture with horns, fins, and layered armor',
      category: 'sculptures',
      size: 'medium',
      image: '/assets/sculpture-creature-front.jpg',
      aspectRatio: '3 / 4',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/sculpture-creature-front'
    },
    {
      id: 'sculpture-creature-profile',
      title: 'Wearable Cardboard Creature — Profile View',
      imageAlt: 'Profile view of a wearable cardboard creature sculpture with layered spines, fins, and a tail',
      category: 'sculptures',
      size: 'medium',
      image: '/assets/sculpture-creature-profile.jpg',
      aspectRatio: '3 / 4',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/sculpture-creature-profile'
    },
    {
      id: 'sculpture-swan-koi-relief',
      title: 'Swan and Koi Relief',
      imageAlt: 'Sculptural relief of a white swan standing over a pond filled with pink and orange koi',
      category: 'sculptures',
      size: 'medium',
      image: '/assets/sculpture-swan-koi-relief.png',
      aspectRatio: '773 / 853',
      objectFit: 'contain',
      showOnHome: true,
      path: '/project/sculpture-swan-koi-relief'
    },
    {
      id: 'animation-pendulum',
      title: '[Placeholder]',
      imageAlt: 'A colorful pendulum character swinging against a blue background',
      category: 'animation',
      size: 'hero',
      image: '/assets/pendulum-example.gif',
      aspectRatio: '16 / 9',
      objectFit: 'contain',
      maxWidth: '960px',
      showOnHome: true,
      path: '/project/animation-pendulum'
    },
    {
      id: 'project-1',
      title: '[Placeholder]',
      imageAlt: 'Winged celestial character surrounded by blue and violet organic forms',
      category: 'illustrations',
      size: 'medium',
      image: '/assets/athena.png',
      showOnHome: false,
      path: '/project/project-1'
    },
    {
      id: 'project-16',
      title: '[Placeholder]',
      imageAlt: 'Blue and violet digital portrait with a red geometric focus over one eye',
      category: 'illustrations',
      size: 'medium',
      image: '/assets/mainpageimage6.jpg',
      showOnHome: true,
      path: '/project/project-16'
    },
    {
      id: 'illustration-10',
      title: 'Illustration 10',
      imageAlt: 'Magenta-toned digital portrait of a dark-haired character wearing pink sunglasses',
      category: 'illustrations',
      size: 'medium',
      image: '/assets/illustration-10.png',
      aspectRatio: '2480 / 3508',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/illustration-10'
    },
    {
      id: 'illustration-axel',
      title: 'Axel — Kingdom Hearts Fan Art',
      imageAlt: 'Fiery digital fan art of Axel from Kingdom Hearts',
      category: 'illustrations',
      size: 'medium',
      image: '/assets/axel-fanart.png',
      aspectRatio: '2480 / 3508',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/illustration-axel'
    },
    {
      id: 'project-sketch',
      title: '[Placeholder]',
      category: 'illustrations',
      size: 'medium',
      image: '/assets/sketch.jpg',
      showOnHome: false,
      path: '/project/project-sketch'
    },
    {
      id: 'project-sketch2',
      title: '[Placeholder]',
      category: 'illustrations',
      size: 'medium',
      image: '/assets/sketch2.jpg',
      showOnHome: false,
      path: '/project/project-sketch2'
    },
    {
      id: 'project-8',
      title: '[Placeholder]',
      imageAlt: 'Cat-eared character with golden eyes against a warm yellow background',
      category: 'commissions',
      size: 'medium',
      image: '/assets/kat.png',
      showOnHome: false,
      path: '/project/project-8'
    },
    {
      id: 'project-12',
      title: '[Placeholder]',
      category: 'commissions',
      size: 'medium',
      image: '/assets/rester.png',
      path: '/project/project-12'
    },
    {
      id: 'comm-3',
      title: '[Placeholder]',
      category: 'commissions',
      size: 'medium',
      image: '/assets/comm_3.png',
      showOnHome: false,
      path: '/project/comm-3'
    },
    {
      id: 'comm-2',
      title: '[Placeholder]',
      category: 'commissions',
      size: 'medium',
      image: '/assets/comm_2.jpg',
      showOnHome: false,
      path: '/project/comm-2'
    },
    {
      id: 'comm-1',
      title: '[Placeholder]',
      category: 'commissions',
      size: 'hero',
      image: '/assets/comm_1.jpg',
      aspectRatio: '1 / 1',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/comm-1'
    },
    {
      id: 'comm-4',
      title: '[Placeholder]',
      category: 'concepts',
      size: 'medium',
      image: '/assets/comm_4.png',
      aspectRatio: '1 / 1',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/comm-4'
    },
    {
      id: 'concept-merow',
      title: '[Placeholder]',
      imageAlt: 'Two illustrated characters debating sushi over the phone',
      category: 'concepts',
      size: 'medium',
      image: '/assets/merow.png',
      aspectRatio: '1 / 1',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/concept-merow'
    },
    {
      id: 'comm-image1',
      title: '[Placeholder]',
      category: 'concepts',
      size: 'medium',
      image: '/assets/image-1.jpg',
      aspectRatio: '1 / 1',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/comm-image1'
    },
    {
      id: 'comm-5',
      title: '[Placeholder]',
      category: 'concepts',
      size: 'medium',
      image: '/assets/comm_5.png',
      aspectRatio: '1 / 1',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/comm-5'
    },
    {
      id: 'concept-example',
      title: '[Placeholder]',
      imageAlt: 'Two illustrated characters posing with drinks and a cat against a blue background',
      category: 'concepts',
      size: 'medium',
      image: '/assets/concept-example.png',
      aspectRatio: '1 / 1',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/concept-example'
    },
    {
      id: 'concept-window-portrait',
      title: '[Placeholder]',
      imageAlt: 'Two illustrated characters standing together in front of an arched window',
      category: 'concepts',
      size: 'medium',
      image: '/assets/concept-window-portrait.png',
      aspectRatio: '1 / 1',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/concept-window-portrait'
    },
    {
      id: 'project-17',
      title: '[Placeholder]',
      imageAlt: 'Teal-haired character posed beside a television in a softly lit room',
      category: 'concepts',
      size: 'medium',
      image: '/assets/concept.jpg',
      aspectRatio: '1 / 1',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/project-17'
    },
    {
      id: 'project-18',
      title: '[Placeholder]',
      imageAlt: 'Two stylized characters together in a dark purple-toned scene',
      category: 'concepts',
      size: 'medium',
      image: '/assets/concept2.png',
      aspectRatio: '1 / 1',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/project-18'
    },
    {
      id: 'concept-3',
      title: '[Placeholder]',
      imageAlt: 'Two stylized characters in a dark teal game-inspired scene with humorous dialogue',
      category: 'concepts',
      size: 'medium',
      image: '/assets/concept3.jpg',
      aspectRatio: '1 / 1',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/concept-3'
    },
    {
      id: 'concept-adventures-of-bingus',
      title: 'Adventures of Bingus',
      imageAlt: 'Two cat-eared characters with oversized swords posed before explosions on an Adventures of Bingus cover',
      category: 'concepts',
      size: 'medium',
      image: '/assets/concept-adventures-of-bingus.jpg',
      aspectRatio: '1 / 1',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/concept-adventures-of-bingus'
    },
    {
      id: 'concept-cowboy-character',
      title: 'Cowboy Character Concept',
      imageAlt: 'Monochrome cowboy character wearing two stacked hats and a scarf on a textured tan background',
      category: 'concepts',
      size: 'medium',
      image: '/assets/concept-cowboy-character.png',
      aspectRatio: '1 / 1',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/concept-cowboy-character'
    },
    {
      id: 'commission-tenko',
      title: 'Tenko Commission',
      imageAlt: 'Cat-eared maid posing with Mudkip, Marill, and Skitty',
      category: 'concepts',
      size: 'medium',
      image: '/assets/commission-tenko.png',
      aspectRatio: '4 / 5',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/commission-tenko'
    },
    {
      id: 'concept-beach-help',
      title: 'Beach Day',
      imageAlt: 'Illustrated character in a black dress on a beach, with someone drowning in the background',
      category: 'concepts',
      size: 'medium',
      image: '/assets/concept-beach-help.jpg',
      aspectRatio: '4 / 5',
      objectFit: 'contain',
      showOnHome: false,
      path: '/project/concept-beach-help'
    }
  ]
};
